language: generic 
sudo: required
services:
 - docker
    
before_install:
 - docker build -t lalitdev90/docker-react -f Dockerfile.dev .
 
script:
 - docker run lalitdev90/docker-react npm run test -- --coverage
